# Mysql数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guns_advanced?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: shc51888
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

    # 连接池大小根据实际情况调整
    max-active: 20
    max-pool-prepared-statement-per-connection-size: 20

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.qq.com
    port: 587
    username: sn93@qq.com
    password: xxxpassword

# 邮件发送（改为自己的账号）
mail:
  from: sn93@qq.com

server:
  port: 9666
